package context

import (
	"crypto/sha1"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"sync"
	"time"
)

type ProjectMapManager struct {
	projectRoot string

	mu                sync.Mutex
	cached            string
	cachedFingerprint string
}

type projectMapState struct {
	Fingerprint string    `json:"fingerprint"`
	GeneratedAt time.Time `json:"generated_at"`
}

func NewProjectMapManager(projectRoot string) *ProjectMapManager {
	return &ProjectMapManager{projectRoot: projectRoot}
}

func (m *ProjectMapManager) Ensure() string {
	if m == nil || m.projectRoot == "" {
		return ""
	}

	fingerprint := m.fingerprint()

	m.mu.Lock()
	defer m.mu.Unlock()

	if m.cached != "" && fingerprint == m.cachedFingerprint {
		return m.cached
	}

	if text, state := m.load(); text != "" && state.Fingerprint == fingerprint {
		m.cached = text
		m.cachedFingerprint = fingerprint
		return text
	}

	text := m.build()
	if strings.TrimSpace(text) == "" {
		return ""
	}
	m.save(text, projectMapState{
		Fingerprint: fingerprint,
		GeneratedAt: time.Now().UTC(),
	})
	m.cached = text
	m.cachedFingerprint = fingerprint
	return text
}

func (m *ProjectMapManager) Refresh() string {
	if m == nil || m.projectRoot == "" {
		return ""
	}
	fingerprint := m.fingerprint()
	text := m.build()
	if strings.TrimSpace(text) == "" {
		return ""
	}

	m.mu.Lock()
	defer m.mu.Unlock()
	m.save(text, projectMapState{
		Fingerprint: fingerprint,
		GeneratedAt: time.Now().UTC(),
	})
	m.cached = text
	m.cachedFingerprint = fingerprint
	return text
}

func (m *ProjectMapManager) build() string {
	root := m.projectRoot
	projectName := filepath.Base(root)
	branch, dirty := gitState(root)

	topEntries, _ := os.ReadDir(root)
	sort.Slice(topEntries, func(i, j int) bool { return topEntries[i].Name() < topEntries[j].Name() })

	stack := detectProjectStack(root)
	layout := describeTopLevelLayout(root, topEntries)
	keyFiles := detectKeyFiles(root)
	patterns := detectRepoPatterns(root)
	currentWork := detectCurrentWork(root, branch, dirty)

	var sections []string
	sections = append(sections, "# Project Map")
	sections = append(sections, "_Generated by Marcus from a bounded repo scan. Refreshes when repo layout or git status changes._")

	sections = append(sections, "## Identity")
	sections = append(sections, "- Project: "+projectName)
	if branch != "" {
		gitLine := "- Git: " + branch
		if dirty {
			gitLine += " (dirty)"
		}
		sections = append(sections, gitLine)
	}

	sections = append(sections, "## Stack")
	if len(stack) == 0 {
		sections = append(sections, "- Stack not inferred yet.")
	} else {
		for _, line := range stack {
			sections = append(sections, "- "+line)
		}
	}

	sections = append(sections, "## Folder structure")
	if len(layout) == 0 {
		sections = append(sections, "- Top-level layout not inferred yet.")
	} else {
		for _, line := range layout {
			sections = append(sections, "- "+line)
		}
	}

	sections = append(sections, "## Key files")
	if len(keyFiles) == 0 {
		sections = append(sections, "- No key files inferred yet.")
	} else {
		for _, line := range keyFiles {
			sections = append(sections, "- "+line)
		}
	}

	sections = append(sections, "## Current work")
	if len(currentWork) == 0 {
		sections = append(sections, "- No active work inferred.")
	} else {
		for _, line := range currentWork {
			sections = append(sections, "- "+line)
		}
	}

	sections = append(sections, "## Patterns in use")
	if len(patterns) == 0 {
		sections = append(sections, "- No strong repo patterns inferred yet.")
	} else {
		for _, line := range patterns {
			sections = append(sections, "- "+line)
		}
	}

	return strings.Join(sections, "\n")
}

func (m *ProjectMapManager) fingerprint() string {
	h := sha1.New()
	write := func(s string) {
		_, _ = h.Write([]byte(s))
		_, _ = h.Write([]byte{'\n'})
	}

	write(m.projectRoot)
	write(strings.TrimSpace(runGit(m.projectRoot, "rev-parse", "--abbrev-ref", "HEAD")))
	write(strings.TrimSpace(runGit(m.projectRoot, "status", "--short")))

	entries, err := os.ReadDir(m.projectRoot)
	if err == nil {
		sort.Slice(entries, func(i, j int) bool { return entries[i].Name() < entries[j].Name() })
		for _, entry := range entries {
			name := entry.Name()
			if shouldSkipProjectMapEntry(name) {
				continue
			}
			write(name)
			if entry.IsDir() {
				children, err := os.ReadDir(filepath.Join(m.projectRoot, name))
				if err != nil {
					continue
				}
				sort.Slice(children, func(i, j int) bool { return children[i].Name() < children[j].Name() })
				for _, child := range children {
					write(name + "/" + child.Name())
				}
			}
		}
	}

	return hex.EncodeToString(h.Sum(nil))
}

func (m *ProjectMapManager) load() (string, projectMapState) {
	var state projectMapState
	data, err := os.ReadFile(m.path())
	if err != nil {
		return "", state
	}
	stateData, err := os.ReadFile(m.statePath())
	if err == nil {
		_ = json.Unmarshal(stateData, &state)
	}
	return string(data), state
}

func (m *ProjectMapManager) save(text string, state projectMapState) {
	dir := filepath.Dir(m.path())
	_ = os.MkdirAll(dir, 0755)
	_ = os.WriteFile(m.path(), []byte(text), 0644)
	if data, err := json.MarshalIndent(state, "", "  "); err == nil {
		_ = os.WriteFile(m.statePath(), data, 0644)
	}
}

func (m *ProjectMapManager) path() string {
	return filepath.Join(m.projectRoot, ".marcus", "context", "PROJECT_MAP.md")
}

func (m *ProjectMapManager) statePath() string {
	return filepath.Join(m.projectRoot, ".marcus", "context", ".project_map_state.json")
}

func detectProjectStack(root string) []string {
	type marker struct {
		path string
		desc string
	}
	markers := []marker{
		{path: "go.mod", desc: "Go module"},
		{path: "package.json", desc: "Node.js package"},
		{path: "tsconfig.json", desc: "TypeScript project"},
		{path: "Cargo.toml", desc: "Rust crate"},
		{path: "pyproject.toml", desc: "Python project"},
		{path: "requirements.txt", desc: "Python requirements"},
		{path: "pom.xml", desc: "Maven project"},
		{path: "build.gradle", desc: "Gradle project"},
		{path: ".marcus/marcus.toml", desc: "Marcus repo-local config"},
	}

	var out []string
	for _, marker := range markers {
		if _, err := os.Stat(filepath.Join(root, marker.path)); err == nil {
			out = append(out, marker.desc+" (`"+filepath.ToSlash(marker.path)+"`)")
		}
	}
	return out
}

func describeTopLevelLayout(root string, entries []os.DirEntry) []string {
	var out []string
	for _, entry := range entries {
		name := entry.Name()
		if shouldSkipProjectMapEntry(name) {
			continue
		}
		if !entry.IsDir() {
			switch name {
			case "go.mod", "package.json", "pyproject.toml", "Cargo.toml", "pom.xml", ".marcus":
			default:
				continue
			}
		}

		desc := describeEntry(root, entry)
		if desc != "" {
			out = append(out, desc)
		}
		if len(out) >= 8 {
			break
		}
	}
	return out
}

func describeEntry(root string, entry os.DirEntry) string {
	name := entry.Name()
	if !entry.IsDir() {
		return fmt.Sprintf("`%s` -> top-level project file", name)
	}

	dir := filepath.Join(root, name)
	children, err := os.ReadDir(dir)
	if err != nil {
		return fmt.Sprintf("`%s/` -> directory", name)
	}
	sort.Slice(children, func(i, j int) bool { return children[i].Name() < children[j].Name() })

	var sample []string
	for _, child := range children {
		childName := child.Name()
		if shouldSkipProjectMapEntry(childName) {
			continue
		}
		if child.IsDir() {
			sample = append(sample, childName)
		}
		if len(sample) >= 5 {
			break
		}
	}

	switch name {
	case ".marcus":
		return "`" + name + "/` -> repo-local agents, flows, context, memory, and tasks"
	case "cmd":
		if len(sample) > 0 {
			return "`cmd/` -> executable entrypoints: " + strings.Join(sample, ", ")
		}
		return "`cmd/` -> executable entrypoints"
	case "internal":
		if len(sample) > 0 {
			return "`internal/` -> core implementation packages: " + strings.Join(sample, ", ")
		}
		return "`internal/` -> core implementation packages"
	case "pkg":
		return "`pkg/` -> reusable exported packages"
	case "src":
		if len(sample) > 0 {
			return "`src/` -> source tree: " + strings.Join(sample, ", ")
		}
		return "`src/` -> source tree"
	case "app":
		if len(sample) > 0 {
			return "`app/` -> application code: " + strings.Join(sample, ", ")
		}
		return "`app/` -> application code"
	case "test", "tests":
		return "`" + name + "/` -> test suite"
	default:
		if len(sample) > 0 {
			return fmt.Sprintf("`%s/` -> contains %s", name, strings.Join(sample, ", "))
		}
		return fmt.Sprintf("`%s/` -> directory", name)
	}
}

func detectKeyFiles(root string) []string {
	seen := map[string]bool{}
	var out []string
	add := func(path, desc string) {
		path = filepath.ToSlash(path)
		if path == "" || seen[path] {
			return
		}
		seen[path] = true
		if desc != "" {
			out = append(out, fmt.Sprintf("`%s` -> %s", path, desc))
		} else {
			out = append(out, fmt.Sprintf("`%s`", path))
		}
	}

	for _, item := range []struct {
		path string
		desc string
	}{
		{path: ".marcus/marcus.toml", desc: "repo-level Marcus config"},
		{path: "go.mod", desc: "Go module definition"},
		{path: "package.json", desc: "Node package manifest"},
		{path: "pyproject.toml", desc: "Python project config"},
		{path: "Cargo.toml", desc: "Rust crate manifest"},
		{path: "README.md", desc: "project overview"},
		{path: "CLAUDE.md", desc: "repo-specific assistant guidance"},
	} {
		if _, err := os.Stat(filepath.Join(root, item.path)); err == nil {
			add(item.path, item.desc)
		}
	}

	addIfFound := func(glob string, desc string, limit int) {
		matches, _ := filepath.Glob(filepath.Join(root, filepath.FromSlash(glob)))
		sort.Strings(matches)
		count := 0
		for _, match := range matches {
			rel, err := filepath.Rel(root, match)
			if err != nil {
				continue
			}
			add(rel, desc)
			count++
			if count >= limit {
				return
			}
		}
	}

	addIfFound("cmd/*/main.go", "entrypoint", 3)
	addIfFound("internal/*/root.go", "load-bearing package root", 2)
	addIfFound("internal/*/app.go", "application entry file", 2)
	addIfFound("src/app/*", "app route or entry area", 2)

	if len(out) > 8 {
		out = out[:8]
	}
	return out
}

func detectCurrentWork(root, branch string, dirty bool) []string {
	var out []string
	if branch != "" {
		branchLine := "Active branch: `" + branch + "`"
		if dirty {
			branchLine += " with uncommitted changes"
		}
		out = append(out, branchLine)
	}

	status := strings.TrimSpace(runGit(root, "status", "--short"))
	if status == "" {
		if branch == "" {
			return out
		}
		out = append(out, "Working tree is clean.")
		return out
	}

	lines := strings.Split(status, "\n")
	var changed []string
	areas := map[string]bool{}
	for _, line := range lines {
		line = strings.TrimSpace(line)
		if line == "" {
			continue
		}
		fields := strings.Fields(line)
		path := fields[len(fields)-1]
		path = filepath.ToSlash(path)
		changed = append(changed, "`"+path+"`")
		area := topLevelArea(path)
		if area != "" {
			areas[area] = true
		}
		if len(changed) >= 5 {
			break
		}
	}
	if len(changed) > 0 {
		out = append(out, "Recently changed files: "+strings.Join(changed, ", "))
	}
	if len(areas) > 0 {
		var ordered []string
		for area := range areas {
			ordered = append(ordered, "`"+area+"`")
		}
		sort.Strings(ordered)
		out = append(out, "Changed areas: "+strings.Join(ordered, ", "))
	}
	return out
}

func detectRepoPatterns(root string) []string {
	var out []string
	if _, err := os.Stat(filepath.Join(root, ".marcus", "agents")); err == nil {
		out = append(out, "Agent behavior is configured under `.marcus/agents/`.")
	}
	if _, err := os.Stat(filepath.Join(root, ".marcus", "flows")); err == nil {
		out = append(out, "Repo-local workflows live under `.marcus/flows/`.")
	}
	if _, err := os.Stat(filepath.Join(root, "internal")); err == nil {
		out = append(out, "Implementation code is concentrated in `internal/`.")
	}
	if _, err := os.Stat(filepath.Join(root, "cmd")); err == nil {
		out = append(out, "Executable entrypoints follow the `cmd/<name>/` pattern.")
	}
	if hasSuffixFile(root, "_test.go") {
		out = append(out, "Go tests use colocated `*_test.go` files.")
	}
	if len(out) > 6 {
		out = out[:6]
	}
	return out
}

func shouldSkipProjectMapEntry(name string) bool {
	switch name {
	case "", ".", "..", ".git", "node_modules", ".venv", "__pycache__":
		return true
	}
	return false
}

func topLevelArea(path string) string {
	path = strings.TrimSpace(filepath.ToSlash(path))
	if path == "" {
		return ""
	}
	if idx := strings.Index(path, "/"); idx != -1 {
		return path[:idx]
	}
	return path
}

func hasSuffixFile(root, suffix string) bool {
	found := false
	_ = filepath.WalkDir(root, func(path string, d os.DirEntry, err error) error {
		if err != nil || found {
			return err
		}
		name := d.Name()
		if d.IsDir() && shouldSkipProjectMapEntry(name) {
			return filepath.SkipDir
		}
		if !d.IsDir() && strings.HasSuffix(name, suffix) {
			found = true
			return filepath.SkipAll
		}
		return nil
	})
	return found
}
