package tool

import (
	"context"
	"encoding/json"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"sync"
	"time"

	"github.com/marcus-ai/marcus/internal/codeintel"
	"github.com/marcus-ai/marcus/internal/diff"
)

// ToolRunner executes tools
type ToolRunner struct {
	baseDir     string
	tools       map[string]Tool
	definitions map[string]Definition
	allowed     map[string]struct{}
}

// NewToolRunner creates a new tool runner
func NewToolRunner() *ToolRunner {
	return &ToolRunner{
		tools:       make(map[string]Tool),
		definitions: make(map[string]Definition),
	}
}

// Register registers a tool
func (tr *ToolRunner) Register(tool Tool) {
	tr.RegisterWithDefinition(tool, defaultDefinition(tool))
}

// Run executes a tool by name
func (tr *ToolRunner) Run(ctx context.Context, name string, input json.RawMessage) (json.RawMessage, error) {
	if err := tr.ensureAllowed(name); err != nil {
		return nil, err
	}
	tool, ok := tr.tools[name]
	if !ok {
		return nil, fmt.Errorf("tool not found: %s", name)
	}
	return tool.Run(ctx, input)
}

// List returns the names of all registered tools.
func (tr *ToolRunner) List() []string {
	names := make([]string, 0, len(tr.tools))
	for name := range tr.tools {
		names = append(names, name)
	}
	return names
}

// ActionProposal is a structured action generated by Marcus.
type ActionProposal struct {
	ID         string         `json:"id"`
	Type       string         `json:"type"`
	Input      map[string]any `json:"input,omitempty"`
	Path       string         `json:"path,omitempty"`
	Content    string         `json:"content,omitempty"`
	Append     bool           `json:"append,omitempty"`
	Command    string         `json:"command,omitempty"`
	Dir        string         `json:"dir,omitempty"`
	Pattern    string         `json:"pattern,omitempty"`
	Symbol     string         `json:"symbol,omitempty"`
	Regex      bool           `json:"regex,omitempty"`
	MaxResults int            `json:"max_results,omitempty"`
	Reason     string         `json:"reason,omitempty"`
}

func (a ActionProposal) Label() string {
	switch a.Type {
	case "write_file":
		return fmt.Sprintf("write %s", a.Path)
	case "run_command":
		return fmt.Sprintf("run %s", a.Command)
	case "search_code":
		return fmt.Sprintf("search %s", a.Pattern)
	case "list_files":
		return fmt.Sprintf("list files in %s", valueOr(a.Path, "."))
	case "read_file":
		return fmt.Sprintf("read %s", a.Path)
	case "find_symbol":
		return fmt.Sprintf("find symbol %s", a.Symbol)
	default:
		return "run " + a.Type
	}
}

func (a ActionProposal) Payload() json.RawMessage {
	if len(a.Input) > 0 {
		payload, _ := json.Marshal(a.Input)
		return payload
	}
	payload, _ := json.Marshal(map[string]any{
		"path":        a.Path,
		"content":     a.Content,
		"append":      a.Append,
		"command":     a.Command,
		"dir":         a.Dir,
		"pattern":     a.Pattern,
		"symbol":      a.Symbol,
		"regex":       a.Regex,
		"max_results": a.MaxResults,
	})
	return payload
}

// ActionPreview is a non-destructive view of a proposal.
type ActionPreview struct {
	Proposal ActionProposal
	Summary  string
	Diff     string
}

// ActionResult captures the result of an applied action.
type ActionResult struct {
	Proposal ActionProposal
	Summary  string
	Diff     string
	Output   string
	ExitCode int
	Success  bool
}

// PreviewAction generates a preview for a proposal without mutating state.
func (tr *ToolRunner) PreviewAction(proposal ActionProposal) (ActionPreview, error) {
	switch proposal.Type {
	case "write_file":
		path, err := tr.resolvePath(proposal.Path)
		if err != nil {
			return ActionPreview{}, err
		}
		current, readErr := os.ReadFile(path)
		if readErr != nil && !isNotExist(readErr) {
			return ActionPreview{}, fmt.Errorf("read current file: %w", readErr)
		}
		next := proposal.Content
		if proposal.Append && len(current) > 0 {
			next = string(current) + proposal.Content
		}
		d, err := diff.GenerateDiff(string(current), next)
		if err != nil {
			return ActionPreview{}, fmt.Errorf("generate diff: %w", err)
		}
		summary := fmt.Sprintf("Write %d bytes to %s", len(next), proposal.Path)
		if isNotExist(readErr) {
			summary = fmt.Sprintf("Create %s (%d bytes)", proposal.Path, len(next))
		}
		return ActionPreview{Proposal: proposal, Summary: summary, Diff: d}, nil
	case "run_command":
		dir := proposal.Dir
		if dir == "" {
			dir = tr.baseDir
		}
		return ActionPreview{
			Proposal: proposal,
			Summary:  fmt.Sprintf("Run %q in %s", proposal.Command, dir),
		}, nil
	case "search_code":
		scope := proposal.Path
		if scope == "" {
			scope = "."
		}
		return ActionPreview{
			Proposal: proposal,
			Summary:  fmt.Sprintf("Search for %q in %s", proposal.Pattern, scope),
		}, nil
	case "list_files":
		scope := proposal.Path
		if scope == "" {
			scope = "."
		}
		return ActionPreview{
			Proposal: proposal,
			Summary:  fmt.Sprintf("List files in %s", scope),
		}, nil
	case "read_file":
		return ActionPreview{
			Proposal: proposal,
			Summary:  fmt.Sprintf("Read %s", proposal.Path),
		}, nil
	case "find_symbol":
		scope := proposal.Path
		if scope == "" {
			scope = "."
		}
		return ActionPreview{
			Proposal: proposal,
			Summary:  fmt.Sprintf("Find symbol %q in %s", proposal.Symbol, scope),
		}, nil
	default:
		if def, ok := tr.Definition(proposal.Type); ok {
			return ActionPreview{
				Proposal: proposal,
				Summary:  fmt.Sprintf("Run tool %s (%s)", def.Name, def.Description),
			}, nil
		}
		return ActionPreview{}, fmt.Errorf("unsupported proposal type: %s", proposal.Type)
	}
}

// ApplyAction executes a structured proposal.
func (tr *ToolRunner) ApplyAction(ctx context.Context, proposal ActionProposal) (ActionResult, error) {
	preview, err := tr.PreviewAction(proposal)
	if err != nil {
		return ActionResult{}, err
	}
	switch proposal.Type {
	case "write_file":
		payload, _ := json.Marshal(map[string]any{
			"path":    proposal.Path,
			"content": proposal.Content,
			"append":  proposal.Append,
		})
		if _, err := tr.Run(ctx, "write_file", payload); err != nil {
			return ActionResult{}, err
		}
		if listTool, ok := tr.tools["list_files"].(*ListFilesTool); ok {
			listTool.invalidate()
		}
		return ActionResult{
			Proposal: proposal,
			Summary:  preview.Summary,
			Diff:     preview.Diff,
			Success:  true,
		}, nil
	case "run_command":
		payload, _ := json.Marshal(map[string]any{
			"command": proposal.Command,
			"dir":     proposal.Dir,
		})
		out, err := tr.Run(ctx, "run_command", payload)
		if err != nil {
			return ActionResult{}, err
		}
		var result struct {
			Output   string `json:"output"`
			ExitCode int    `json:"exit_code"`
		}
		_ = json.Unmarshal(out, &result)
		return ActionResult{
			Proposal: proposal,
			Summary:  preview.Summary,
			Output:   result.Output,
			ExitCode: result.ExitCode,
			Success:  result.ExitCode == 0,
		}, nil
	case "search_code":
		payload, _ := json.Marshal(map[string]any{
			"pattern":     proposal.Pattern,
			"path":        proposal.Path,
			"regex":       proposal.Regex,
			"max_results": proposal.MaxResults,
		})
		out, err := tr.Run(ctx, "search_code", payload)
		if err != nil {
			return ActionResult{}, err
		}
		return ActionResult{
			Proposal: proposal,
			Summary:  preview.Summary,
			Output:   formatSearchOutput(out),
			Success:  true,
		}, nil
	case "list_files":
		payload, _ := json.Marshal(map[string]any{
			"path":        proposal.Path,
			"max_results": proposal.MaxResults,
		})
		out, err := tr.Run(ctx, "list_files", payload)
		if err != nil {
			return ActionResult{}, err
		}
		return ActionResult{
			Proposal: proposal,
			Summary:  preview.Summary,
			Output:   formatListFilesOutput(out),
			Success:  true,
		}, nil
	case "read_file":
		payload, _ := json.Marshal(map[string]any{
			"path": proposal.Path,
		})
		out, err := tr.Run(ctx, "read_file", payload)
		if err != nil {
			return ActionResult{}, err
		}
		return ActionResult{
			Proposal: proposal,
			Summary:  preview.Summary,
			Output:   formatReadFileOutput(out),
			Success:  true,
		}, nil
	case "find_symbol":
		out, err := tr.Run(ctx, "find_symbol", proposal.Payload())
		if err != nil {
			return ActionResult{}, err
		}
		return ActionResult{
			Proposal: proposal,
			Summary:  preview.Summary,
			Output:   formatFindSymbolOutput(out),
			Success:  true,
		}, nil
	default:
		out, err := tr.Run(ctx, proposal.Type, proposal.Payload())
		if err != nil {
			return ActionResult{}, err
		}
		return ActionResult{
			Proposal: proposal,
			Summary:  preview.Summary,
			Output:   formatGenericOutput(out),
			Success:  true,
		}, nil
	}
}

func (tr *ToolRunner) resolvePath(path string) (string, error) {
	if filepath.IsAbs(path) {
		return ensureWithinBaseDir(tr.baseDir, path)
	}
	if tr.baseDir == "" {
		return filepath.Abs(path)
	}
	return ensureWithinBaseDir(tr.baseDir, filepath.Join(tr.baseDir, path))
}

// Tool defines the interface for a Marcus tool
type Tool interface {
	Name() string
	Description() string
	Schema() JSONSchema
	Run(ctx context.Context, input json.RawMessage) (json.RawMessage, error)
}

// JSONSchema defines a tool's input schema
type JSONSchema struct {
	Type       string                   `json:"type"`
	Properties map[string]*JSONProperty `json:"properties,omitempty"`
	Required   []string                 `json:"required,omitempty"`
}

type JSONProperty struct {
	Type        string `json:"type"`
	Description string `json:"description"`
}

// ReadFileTool reads a file's contents
type ReadFileTool struct {
	baseDir string
}

// NewReadFileTool creates a new read_file tool
func NewReadFileTool(baseDir string) *ReadFileTool {
	return &ReadFileTool{baseDir: baseDir}
}

func (t *ReadFileTool) Name() string        { return "read_file" }
func (t *ReadFileTool) Description() string { return "Read the contents of a file" }

func (t *ReadFileTool) Schema() JSONSchema {
	return JSONSchema{
		Type: "object",
		Properties: map[string]*JSONProperty{
			"path": {Type: "string", Description: "Path to the file"},
		},
		Required: []string{"path"},
	}
}

func (t *ReadFileTool) Run(ctx context.Context, input json.RawMessage) (json.RawMessage, error) {
	var params struct {
		Path string `json:"path"`
	}
	if err := json.Unmarshal(input, &params); err != nil {
		return nil, fmt.Errorf("unmarshal input: %w", err)
	}

	path, err := resolveToolPath(t.baseDir, params.Path)
	if err != nil {
		return nil, err
	}

	content, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("read file: %w", err)
	}

	result := map[string]interface{}{
		"path":    params.Path,
		"content": string(content),
		"size":    len(content),
	}

	return json.Marshal(result)
}

// ListFilesTool lists files inside a directory.
type ListFilesTool struct {
	baseDir string
	mu      sync.RWMutex
	cached  []string
}

// NewListFilesTool creates a new list_files tool.
func NewListFilesTool(baseDir string) *ListFilesTool {
	return &ListFilesTool{baseDir: baseDir}
}

func (t *ListFilesTool) Name() string        { return "list_files" }
func (t *ListFilesTool) Description() string { return "List files inside a directory" }

func (t *ListFilesTool) Schema() JSONSchema {
	return JSONSchema{
		Type: "object",
		Properties: map[string]*JSONProperty{
			"path":        {Type: "string", Description: "Optional directory to inspect"},
			"max_results": {Type: "number", Description: "Maximum number of results"},
		},
	}
}

func (t *ListFilesTool) Run(ctx context.Context, input json.RawMessage) (json.RawMessage, error) {
	var params struct {
		Path       string `json:"path"`
		MaxResults int    `json:"max_results"`
	}
	if err := json.Unmarshal(input, &params); err != nil {
		return nil, fmt.Errorf("unmarshal input: %w", err)
	}
	if params.MaxResults <= 0 {
		params.MaxResults = 50
	}
	files, err := t.listFiles(ctx, params.Path)
	if err != nil {
		return nil, err
	}
	if len(files) > params.MaxResults {
		files = files[:params.MaxResults]
	}
	return json.Marshal(map[string]any{
		"path":  valueOr(params.Path, "."),
		"count": len(files),
		"files": files,
	})
}

func (t *ListFilesTool) listFiles(ctx context.Context, scope string) ([]string, error) {
	if t.baseDir == "" {
		t.baseDir, _ = os.Getwd()
	}
	t.mu.RLock()
	cached := append([]string(nil), t.cached...)
	t.mu.RUnlock()
	if len(cached) == 0 {
		var err error
		cached, err = t.buildCache(ctx)
		if err != nil {
			return nil, err
		}
	}
	scope = filepath.ToSlash(strings.TrimSpace(scope))
	if scope == "" || scope == "." {
		return cached, nil
	}
	var filtered []string
	for _, file := range cached {
		if file == scope || strings.HasPrefix(file, scope+"/") || strings.Contains(strings.ToLower(file), strings.ToLower(scope)) {
			filtered = append(filtered, file)
		}
	}
	return filtered, nil
}

func (t *ListFilesTool) buildCache(ctx context.Context) ([]string, error) {
	var files []string
	err := filepath.WalkDir(t.baseDir, func(path string, d os.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		select {
		case <-ctx.Done():
			return ctx.Err()
		default:
		}
		if d.IsDir() {
			name := d.Name()
			if name == ".git" || name == "node_modules" || name == ".venv" || name == "__pycache__" {
				return filepath.SkipDir
			}
			return nil
		}
		rel, _ := filepath.Rel(t.baseDir, path)
		files = append(files, filepath.ToSlash(rel))
		return nil
	})
	if err != nil {
		return nil, err
	}
	sort.Strings(files)
	t.mu.Lock()
	t.cached = append([]string(nil), files...)
	t.mu.Unlock()
	return files, nil
}

func (t *ListFilesTool) invalidate() {
	t.mu.Lock()
	t.cached = nil
	t.mu.Unlock()
}

// WriteFileTool writes content to a file
type WriteFileTool struct {
	baseDir string
}

// NewWriteFileTool creates a new write_file tool
func NewWriteFileTool(baseDir string) *WriteFileTool {
	return &WriteFileTool{baseDir: baseDir}
}

func (t *WriteFileTool) Name() string        { return "write_file" }
func (t *WriteFileTool) Description() string { return "Write content to a file" }

func (t *WriteFileTool) Schema() JSONSchema {
	return JSONSchema{
		Type: "object",
		Properties: map[string]*JSONProperty{
			"path":    {Type: "string", Description: "Path to the file"},
			"content": {Type: "string", Description: "Content to write"},
			"append":  {Type: "boolean", Description: "Append instead of overwrite"},
		},
		Required: []string{"path", "content"},
	}
}

func (t *WriteFileTool) Run(ctx context.Context, input json.RawMessage) (json.RawMessage, error) {
	var params struct {
		Path    string `json:"path"`
		Content string `json:"content"`
		Append  bool   `json:"append"`
	}
	if err := json.Unmarshal(input, &params); err != nil {
		return nil, fmt.Errorf("unmarshal input: %w", err)
	}

	path, err := resolveToolPath(t.baseDir, params.Path)
	if err != nil {
		return nil, err
	}

	// Create parent directory if needed
	dir := filepath.Dir(path)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return nil, fmt.Errorf("create dir: %w", err)
	}

	if params.Append {
		f, err := os.OpenFile(path, os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0644)
		if err != nil {
			return nil, fmt.Errorf("open append file: %w", err)
		}
		defer f.Close()
		if _, err := f.WriteString(params.Content); err != nil {
			return nil, fmt.Errorf("append file: %w", err)
		}
	} else {
		if err := os.WriteFile(path, []byte(params.Content), 0644); err != nil {
			return nil, fmt.Errorf("write file: %w", err)
		}
	}

	result := map[string]interface{}{
		"path":    params.Path,
		"written": true,
		"size":    len(params.Content),
	}

	return json.Marshal(result)
}

// SearchCodeTool looks for a pattern across repo files.
type SearchCodeTool struct {
	baseDir string
	index   *codeintel.Index
}

// NewSearchCodeTool creates a new search_code tool.
func NewSearchCodeTool(baseDir string) *SearchCodeTool {
	return &SearchCodeTool{baseDir: baseDir}
}

func NewSearchCodeToolWithIndex(baseDir string, index *codeintel.Index) *SearchCodeTool {
	return &SearchCodeTool{baseDir: baseDir, index: index}
}

func (t *SearchCodeTool) Name() string        { return "search_code" }
func (t *SearchCodeTool) Description() string { return "Search for a code pattern across files" }

func (t *SearchCodeTool) Schema() JSONSchema {
	return JSONSchema{
		Type: "object",
		Properties: map[string]*JSONProperty{
			"pattern":     {Type: "string", Description: "Literal text or regex to search"},
			"path":        {Type: "string", Description: "Optional directory scope"},
			"regex":       {Type: "boolean", Description: "Interpret pattern as regex"},
			"max_results": {Type: "number", Description: "Maximum number of matches"},
		},
		Required: []string{"pattern"},
	}
}

func (t *SearchCodeTool) Run(ctx context.Context, input json.RawMessage) (json.RawMessage, error) {
	var params struct {
		Pattern    string `json:"pattern"`
		Path       string `json:"path"`
		Regex      bool   `json:"regex"`
		MaxResults int    `json:"max_results"`
	}
	if err := json.Unmarshal(input, &params); err != nil {
		return nil, fmt.Errorf("unmarshal input: %w", err)
	}
	if strings.TrimSpace(params.Pattern) == "" {
		return nil, fmt.Errorf("pattern is required")
	}
	if params.MaxResults <= 0 {
		params.MaxResults = 20
	}

	searchRoot := t.baseDir
	if params.Path != "" {
		resolved, err := resolveToolPath(t.baseDir, params.Path)
		if err != nil {
			return nil, err
		}
		searchRoot = resolved
	}
	if searchRoot == "" {
		searchRoot, _ = os.Getwd()
	}

	if t.index != nil {
		matches := t.index.Search(params.Pattern, params.Path, params.Regex, params.MaxResults)
		return json.Marshal(map[string]any{
			"pattern": params.Pattern,
			"count":   len(matches),
			"matches": matches,
		})
	}

	var matcher *regexp.Regexp
	var err error
	if params.Regex {
		matcher, err = regexp.Compile(params.Pattern)
		if err != nil {
			return nil, fmt.Errorf("compile regex: %w", err)
		}
	}

	baseDir := t.baseDir
	if baseDir == "" {
		baseDir = searchRoot
	}

	type match struct {
		Path    string `json:"path"`
		Line    int    `json:"line"`
		Preview string `json:"preview"`
	}
	var matches []match

	err = filepath.WalkDir(searchRoot, func(path string, d os.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		select {
		case <-ctx.Done():
			return ctx.Err()
		default:
		}
		if d.IsDir() {
			name := d.Name()
			if name == ".git" || name == "node_modules" || name == ".venv" || name == "__pycache__" {
				return filepath.SkipDir
			}
			return nil
		}
		info, err := d.Info()
		if err != nil || info.Size() > 1_000_000 {
			return nil
		}
		content, err := os.ReadFile(path)
		if err != nil {
			return nil
		}
		lines := strings.Split(string(content), "\n")
		for i, line := range lines {
			matched := false
			if params.Regex {
				matched = matcher.MatchString(line)
			} else {
				matched = strings.Contains(line, params.Pattern)
			}
			if matched {
				rel, _ := filepath.Rel(baseDir, path)
				matches = append(matches, match{
					Path:    filepath.ToSlash(rel),
					Line:    i + 1,
					Preview: strings.TrimSpace(line),
				})
				if len(matches) >= params.MaxResults {
					return filepath.SkipAll
				}
			}
		}
		return nil
	})
	if err != nil && err != filepath.SkipAll {
		return nil, err
	}

	sort.Slice(matches, func(i, j int) bool {
		if matches[i].Path == matches[j].Path {
			return matches[i].Line < matches[j].Line
		}
		return matches[i].Path < matches[j].Path
	})

	return json.Marshal(map[string]any{
		"pattern": params.Pattern,
		"count":   len(matches),
		"matches": matches,
	})
}

// FindSymbolTool locates likely definitions for a symbol name.
type FindSymbolTool struct {
	baseDir string
	index   *codeintel.Index
}

// NewFindSymbolTool creates a new find_symbol tool.
func NewFindSymbolTool(baseDir string) *FindSymbolTool {
	return &FindSymbolTool{baseDir: baseDir}
}

func NewFindSymbolToolWithIndex(baseDir string, index *codeintel.Index) *FindSymbolTool {
	return &FindSymbolTool{baseDir: baseDir, index: index}
}

func (t *FindSymbolTool) Name() string { return "find_symbol" }
func (t *FindSymbolTool) Description() string {
	return "Find likely symbol definitions across the repo"
}

func (t *FindSymbolTool) Schema() JSONSchema {
	return JSONSchema{
		Type: "object",
		Properties: map[string]*JSONProperty{
			"symbol":      {Type: "string", Description: "Symbol or method name to find"},
			"path":        {Type: "string", Description: "Optional directory scope"},
			"max_results": {Type: "number", Description: "Maximum number of matches"},
		},
		Required: []string{"symbol"},
	}
}

func (t *FindSymbolTool) Run(ctx context.Context, input json.RawMessage) (json.RawMessage, error) {
	var params struct {
		Symbol     string `json:"symbol"`
		Path       string `json:"path"`
		MaxResults int    `json:"max_results"`
	}
	if err := json.Unmarshal(input, &params); err != nil {
		return nil, fmt.Errorf("unmarshal input: %w", err)
	}
	if strings.TrimSpace(params.Symbol) == "" {
		return nil, fmt.Errorf("symbol is required")
	}
	if params.MaxResults <= 0 {
		params.MaxResults = 20
	}

	searchRoot := t.baseDir
	if params.Path != "" {
		resolved, err := resolveToolPath(t.baseDir, params.Path)
		if err != nil {
			return nil, err
		}
		searchRoot = resolved
	}
	if searchRoot == "" {
		searchRoot, _ = os.Getwd()
	}
	baseDir := t.baseDir
	if baseDir == "" {
		baseDir = searchRoot
	}

	if t.index != nil {
		symbols := t.index.FindSymbol(params.Symbol, params.Path, params.MaxResults)
		type match struct {
			Path    string `json:"path"`
			Line    int    `json:"line"`
			Preview string `json:"preview"`
			Kind    string `json:"kind,omitempty"`
			Score   int    `json:"-"`
		}
		matches := make([]match, 0, len(symbols))
		for _, symbol := range symbols {
			matches = append(matches, match{
				Path:    symbol.Path,
				Line:    symbol.Line,
				Preview: valueOr(symbol.Signature, symbol.Name),
				Kind:    symbol.Kind,
				Score:   100,
			})
		}
		return json.Marshal(map[string]any{
			"symbol":  params.Symbol,
			"count":   len(matches),
			"matches": matches,
		})
	}

	type match struct {
		Path    string `json:"path"`
		Line    int    `json:"line"`
		Preview string `json:"preview"`
		Kind    string `json:"kind,omitempty"`
		Score   int    `json:"-"`
	}
	var matches []match

	err := filepath.WalkDir(searchRoot, func(path string, d os.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		select {
		case <-ctx.Done():
			return ctx.Err()
		default:
		}
		if d.IsDir() {
			name := d.Name()
			if name == ".git" || name == "node_modules" || name == ".venv" || name == "__pycache__" {
				return filepath.SkipDir
			}
			return nil
		}
		info, err := d.Info()
		if err != nil || info.Size() > 1_000_000 {
			return nil
		}
		content, err := os.ReadFile(path)
		if err != nil {
			return nil
		}
		rel, _ := filepath.Rel(baseDir, path)
		relPath := filepath.ToSlash(rel)

		fileMatches := findSymbolMatches(path, relPath, string(content), params.Symbol)
		for _, found := range fileMatches {
			matches = append(matches, match(found))
			if len(matches) >= params.MaxResults {
				return filepath.SkipAll
			}
		}
		return nil
	})
	if err != nil && err != filepath.SkipAll {
		return nil, err
	}

	sort.Slice(matches, func(i, j int) bool {
		if matches[i].Score == matches[j].Score {
			if matches[i].Path == matches[j].Path {
				return matches[i].Line < matches[j].Line
			}
			return matches[i].Path < matches[j].Path
		}
		return matches[i].Score > matches[j].Score
	})
	if len(matches) > params.MaxResults {
		matches = matches[:params.MaxResults]
	}

	return json.Marshal(map[string]any{
		"symbol":  params.Symbol,
		"count":   len(matches),
		"matches": matches,
	})
}

type symbolMatch struct {
	Path    string
	Line    int
	Preview string
	Kind    string
	Score   int
}

func findSymbolMatches(absPath, relPath, content, symbol string) []symbolMatch {
	ext := strings.ToLower(filepath.Ext(absPath))
	if ext == ".go" {
		if matches := findGoSymbolMatches(absPath, relPath, content, symbol); len(matches) > 0 {
			return matches
		}
	}
	return findPatternSymbolMatches(relPath, content, symbol)
}

func findGoSymbolMatches(absPath, relPath, content, symbol string) []symbolMatch {
	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, absPath, content, parser.ParseComments)
	if err != nil {
		return nil
	}
	lines := strings.Split(content, "\n")
	var matches []symbolMatch
	for _, decl := range file.Decls {
		switch d := decl.(type) {
		case *ast.FuncDecl:
			if d.Name == nil || d.Name.Name != symbol {
				continue
			}
			kind := "func"
			score := 95
			if d.Recv != nil {
				kind = "method"
				score = 100
			}
			line := fset.Position(d.Pos()).Line
			matches = append(matches, symbolMatch{
				Path:    relPath,
				Line:    line,
				Preview: previewLine(lines, line),
				Kind:    kind,
				Score:   score,
			})
		case *ast.GenDecl:
			for _, spec := range d.Specs {
				switch s := spec.(type) {
				case *ast.TypeSpec:
					if s.Name.Name != symbol {
						continue
					}
					line := fset.Position(s.Pos()).Line
					matches = append(matches, symbolMatch{
						Path:    relPath,
						Line:    line,
						Preview: previewLine(lines, line),
						Kind:    "type",
						Score:   90,
					})
				case *ast.ValueSpec:
					for _, name := range s.Names {
						if name.Name != symbol {
							continue
						}
						line := fset.Position(name.Pos()).Line
						kind := "var"
						score := 75
						if d.Tok == token.CONST {
							kind = "const"
							score = 80
						}
						matches = append(matches, symbolMatch{
							Path:    relPath,
							Line:    line,
							Preview: previewLine(lines, line),
							Kind:    kind,
							Score:   score,
						})
					}
				}
			}
		}
	}
	return matches
}

func findPatternSymbolMatches(relPath, content, symbol string) []symbolMatch {
	type candidate struct {
		re    *regexp.Regexp
		kind  string
		score int
	}
	candidates := []candidate{
		{regexp.MustCompile(`^\s*def\s+` + regexp.QuoteMeta(symbol) + `\b`), "function", 95},
		{regexp.MustCompile(`^\s*class\s+` + regexp.QuoteMeta(symbol) + `\b`), "class", 92},
		{regexp.MustCompile(`^\s*func\s+(?:\([^)]+\)\s*)?` + regexp.QuoteMeta(symbol) + `\b`), "func", 95},
		{regexp.MustCompile(`^\s*type\s+` + regexp.QuoteMeta(symbol) + `\b`), "type", 90},
		{regexp.MustCompile(`^\s*function\s+` + regexp.QuoteMeta(symbol) + `\b`), "function", 90},
		{regexp.MustCompile(`^\s*(?:async\s+)?(?:const|let|var)\s+` + regexp.QuoteMeta(symbol) + `\s*=\s*(?:async\s*)?\(`), "function", 88},
		{regexp.MustCompile(`^\s*(?:const|let|var)\s+` + regexp.QuoteMeta(symbol) + `\b`), "variable", 75},
		{regexp.MustCompile(`^\s*` + regexp.QuoteMeta(symbol) + `\s*[:=]\s*(?:async\s*)?\(`), "function", 82},
		{regexp.MustCompile(`^\s*` + regexp.QuoteMeta(symbol) + `\s*\(`), "call_or_definition", 45},
	}

	lines := strings.Split(content, "\n")
	var matches []symbolMatch
	for i, line := range lines {
		for _, candidate := range candidates {
			if candidate.re.MatchString(line) {
				matches = append(matches, symbolMatch{
					Path:    relPath,
					Line:    i + 1,
					Preview: strings.TrimSpace(line),
					Kind:    candidate.kind,
					Score:   candidate.score,
				})
				break
			}
		}
	}
	return matches
}

func previewLine(lines []string, line int) string {
	if line <= 0 || line > len(lines) {
		return ""
	}
	return strings.TrimSpace(lines[line-1])
}

// RunCommandTool runs a shell command
type RunCommandTool struct {
	dir     string
	timeout time.Duration
}

// NewRunCommandTool creates a new run_command tool
func NewRunCommandTool(dir string, timeout time.Duration) *RunCommandTool {
	return &RunCommandTool{dir: dir, timeout: timeout}
}

func (t *RunCommandTool) Name() string        { return "run_command" }
func (t *RunCommandTool) Description() string { return "Run a shell command" }

func (t *RunCommandTool) Schema() JSONSchema {
	return JSONSchema{
		Type: "object",
		Properties: map[string]*JSONProperty{
			"command": {Type: "string", Description: "Command to run"},
			"dir":     {Type: "string", Description: "Working directory"},
		},
		Required: []string{"command"},
	}
}

func (t *RunCommandTool) Run(ctx context.Context, input json.RawMessage) (json.RawMessage, error) {
	var params struct {
		Command string `json:"command"`
		Dir     string `json:"dir"`
	}
	if err := json.Unmarshal(input, &params); err != nil {
		return nil, fmt.Errorf("unmarshal input: %w", err)
	}
	params.Command = normalizeCommandForShell(params.Command)

	// Parse command
	var cmd *exec.Cmd
	if filepath.Separator == '\\' {
		// Windows
		cmd = exec.CommandContext(ctx, "cmd", "/c", params.Command)
	} else {
		cmd = exec.CommandContext(ctx, "sh", "-c", params.Command)
	}

	if t.timeout > 0 {
		var cancel context.CancelFunc
		ctx, cancel = context.WithTimeout(ctx, t.timeout)
		defer cancel()
		if filepath.Separator == '\\' {
			cmd = exec.CommandContext(ctx, "cmd", "/c", params.Command)
		} else {
			cmd = exec.CommandContext(ctx, "sh", "-c", params.Command)
		}
	}

	if params.Dir != "" {
		dir, err := resolveToolPath(t.dir, params.Dir)
		if err != nil {
			return nil, err
		}
		cmd.Dir = dir
	} else if t.dir != "" {
		cmd.Dir = t.dir
	}

	output, err := cmd.CombinedOutput()
	if err != nil {
		return json.Marshal(map[string]interface{}{
			"command":   params.Command,
			"exit_code": cmd.ProcessState.ExitCode(),
			"output":    string(output),
			"error":     err.Error(),
			"failed":    true,
		})
	}

	return json.Marshal(map[string]interface{}{
		"command":   params.Command,
		"exit_code": 0,
		"output":    string(output),
		"failed":    false,
	})
}

func normalizeCommandForShell(command string) string {
	command = strings.TrimSpace(command)
	if command == "" {
		return command
	}
	if filepath.Separator == '\\' {
		// Models sometimes emit JSON-escaped quotes in commands. On Windows, Marcus
		// executes through `cmd /c`, so the shell should receive plain quotes.
		command = strings.ReplaceAll(command, `\"`, `"`)
		command = strings.ReplaceAll(command, `\'`, `'`)
	}
	return command
}

func resolveToolPath(baseDir, path string) (string, error) {
	if path == "" {
		return "", nil
	}
	if filepath.IsAbs(path) {
		return ensureWithinBaseDir(baseDir, path)
	}
	if baseDir == "" {
		return filepath.Abs(path)
	}
	return ensureWithinBaseDir(baseDir, filepath.Join(baseDir, path))
}

func ensureWithinBaseDir(baseDir, path string) (string, error) {
	absPath, err := filepath.Abs(path)
	if err != nil {
		return "", err
	}
	if baseDir == "" {
		return absPath, nil
	}
	absBase, err := filepath.Abs(baseDir)
	if err != nil {
		return "", err
	}
	rel, err := filepath.Rel(absBase, absPath)
	if err != nil {
		return "", err
	}
	if rel == ".." || strings.HasPrefix(rel, ".."+string(filepath.Separator)) {
		return "", fmt.Errorf("path escapes baseDir: %s", path)
	}
	return absPath, nil
}

func isNotExist(err error) bool {
	return err != nil && os.IsNotExist(err)
}

func formatSearchOutput(raw json.RawMessage) string {
	var payload struct {
		Count   int `json:"count"`
		Matches []struct {
			Path    string `json:"path"`
			Line    int    `json:"line"`
			Preview string `json:"preview"`
		} `json:"matches"`
	}
	if err := json.Unmarshal(raw, &payload); err != nil {
		return string(raw)
	}
	if payload.Count == 0 {
		return "No matches found."
	}
	var lines []string
	for _, match := range payload.Matches {
		lines = append(lines, fmt.Sprintf("%s:%d %s", match.Path, match.Line, match.Preview))
	}
	return strings.Join(lines, "\n")
}

func formatListFilesOutput(raw json.RawMessage) string {
	var payload struct {
		Files []string `json:"files"`
	}
	if err := json.Unmarshal(raw, &payload); err != nil {
		return string(raw)
	}
	if len(payload.Files) == 0 {
		return "No files found."
	}
	return strings.Join(payload.Files, "\n")
}

func formatReadFileOutput(raw json.RawMessage) string {
	var payload struct {
		Path    string `json:"path"`
		Content string `json:"content"`
	}
	if err := json.Unmarshal(raw, &payload); err != nil {
		return string(raw)
	}
	return fmt.Sprintf("%s\n\n%s", payload.Path, payload.Content)
}

func formatFindSymbolOutput(raw json.RawMessage) string {
	var payload struct {
		Matches []struct {
			Path    string `json:"path"`
			Line    int    `json:"line"`
			Preview string `json:"preview"`
			Kind    string `json:"kind"`
		} `json:"matches"`
	}
	if err := json.Unmarshal(raw, &payload); err != nil {
		return string(raw)
	}
	if len(payload.Matches) == 0 {
		return "No symbol definitions found."
	}
	var lines []string
	for _, match := range payload.Matches {
		label := match.Kind
		if strings.TrimSpace(label) == "" {
			label = "match"
		}
		lines = append(lines, fmt.Sprintf("%s:%d [%s] %s", match.Path, match.Line, label, match.Preview))
	}
	return strings.Join(lines, "\n")
}

func formatGenericOutput(raw json.RawMessage) string {
	var payload map[string]any
	if err := json.Unmarshal(raw, &payload); err != nil {
		return string(raw)
	}
	pretty, err := json.MarshalIndent(payload, "", "  ")
	if err != nil {
		return string(raw)
	}
	return string(pretty)
}

func valueOr(value, fallback string) string {
	if strings.TrimSpace(value) == "" {
		return fallback
	}
	return value
}
